baseURL = 'https://it-irokez.ru/'
languageCode = 'ru-ru'
title = 'Ирокезнутый блог'
publishDir = "docs"
description = "Ирокезнутый блог Александра Васюкова"
enableRobotsTXT = true
# menu = 'main'
[outputs]
    home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

    

[Params]
  description = "Ирокезнутый блог Александра Васюкова"

  [Params.Navbar]
  use = true

  [Params.Extensions]
  use = true
  ext=".md"
  [Params.Terminal]
  scheme = "Molokai"
  userName = "alex"
  pcName = "it-irokez.ru"
  workDir = "Documents"
  profile = "profile.txt"

  ps1Delay = 0 
  stdoutDelay = 0
  commandDelay = 0 

  
  titleDelay = 0
  contentDelay = 0

  description = """
  Привет! Это блог ирокезнутого it-шника 
  Александра Васюкова!
  """


  
  [Params.Tree]
  use = true
  folderName = "Projects"
  files = [ 
    ["summary.md","/summary.md"],
    ["Статьи", "articles"],
    ["Обзоры книг", "books_reviews/"],
    ["GitHub", "https://github.com/Brom95"],
    ["Телеграм канал", "https://itirokez.t.me"],
    ["rss.xml","rss.xml"]
    
  ]